Repository C0DE-BUST3RS/oryx-network, pull requests merged in 2018-08, with the labels that each got.

#10 WIP: Query improvement
  public/img/profilepictures/1535456667.png
  public/includes/functions.inc.php
  public/includes/login.inc.php
  public/includes/requestpw.inc.php
  public/includes/signup.inc.php
Labels: WIP

#13 Upgraded Font Awesome from 4.7.0 to 5.2.0
  public/404.php
  public/api.php
  public/changepw.php
  public/contact.php
  public/css/font-awesome.min.css
  public/css/font-awesome/fontawesome-webfont.svg
  public/css/font-awesome/fontawesome-webfont.ttf
  public/css/font-awesome/fontawesome-webfont.woff
  public/css/font-awesome/fontawesome-webfont.woff2
  public/feed.php
  public/includes/nav-login.php
  public/includes/nav-nologin.php
  public/index.php
  public/login.php
  public/privacy.php
  public/profile.php
  public/requestpw.php
  public/settings.php
Labels: enhancement

#14 Optimized statements
  public/404.php
  public/api.php
  public/contact.php
  public/privacy.php
Labels: enhancement

#15 Fixed a missing logout icon
  public/includes/nav-login.php
Labels: bug

#16 Improved the code
  public/404.php
  public/changepw.php
  public/contact.php
  public/feed.php
  public/includes/activate.php
  public/includes/functions.inc.php
  public/includes/login.inc.php
  public/includes/logout.inc.php
  public/includes/requestpw.inc.php
  public/includes/sendtoken.inc.php
  public/includes/signup.inc.php
  public/index.php
  public/login.php
  public/profile.php
  public/requestpw.php
  public/settings.php
Labels: enhancement

#17 Removed the items in the settings page
  public/settings.php
Labels: enhancement

#18 Removed a bug where signing in and logging in was not possible
  public/changepw.php
  public/includes/functions.inc.php
  public/includes/login.inc.php
  public/includes/signup.inc.php
Labels: bug

#21 Improved the queries
  public/changepw.php
Labels: enhancement

#22 Added ability to post messages
  public/feed.php
  public/includes/post.inc.php
Labels: enhancement

#23 Added delete post function
  public/feed.php
  public/includes/deletepost.inc.php
Labels: enhancement

#24 Improved query
  public/feed.php
Labels: enhancement

#26 Improved the query
  public/feed.php
Labels: enhancement
